global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: container-oomkill
    static_configs:
      - targets: ["exporter:9262"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]
