{
 "title": "Container OOM kills",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "oom/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_oomkills_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rss",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_oomkills_process_stat_rss{} * 4096",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vsize",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_oomkills_process_stat_vsize{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "majflt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "container_oomkills_process_stat_majflt{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "minflt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "container_oomkills_process_stat_minflt{}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}